### ISSUE TITLE
2 instances of Asus Flip Cover installed

### ISSUE THREAD

**Issue by aik** [shakalaca/android_device_asus_ze520kl#6]
And one of them crashes pretty much straight away. I do not have that cover btw.

**Comment by nerthazrim** [comment]
Thanks a lot for your work!

I do have a FlipCover and it works almost perfectly, if it wasn't for the regular crashes that the app does :(

Sometimes the app even crashes when the FlipCover is closed (and the "flip mode" is enabled), locking the phone on the "flip screen". Sometimes the "flip screen" won't appear at all when the Cover has been closed.

Any help? Could you fix that? :)

Thanks!

PS: copying this comment from a closed issue.

**Comment by sultan2304** [comment]
It was fixed in the new version of firmware (30.07)

**Comment by sultan2304** [comment]
Yes, this bug was not fixed..

**Comment by nerthazrim** [comment]
I don't see any crash pop-up anymore regarding the FlipCover but I got again the bug where the FlipMode stays on even when I open the FlipCover. It happened again after a full night of charge.

I had to reboot the phone to get out of the FlipMode, as before the 20170730 build :(

A fix on that would be very welcome. Thanks for your work anyway, it's awesome :)

**Comment by nerthazrim** [comment]
@shakalaca I confirm that the Asus Cover app' is still crashing from times to times.

When it does, the FlipCover mode isn't enabled anymore when the Cover is closed, I need to reboot the phone to get it working again.
Seems like the previous fix didn't work, sorry :(

Thanks again for your work :)
